export const countries = [
     {
          "country": "Afghanistan",
     },
     {
          "country": "Albania",
     }, {
          "country": "Algeria",
     }, {
          "country": "Andorra",
     }, {
          "country": "Angola",
     }, {
          "country": "Antigua and Barbuda",
     }, {
          "country": "Argentina",
     }, {
          "country": "Armenia",
     }, {
          "country": "Australia",
     }, {
          "country": "Austria",
     }, {
          "country": "Azerbaijan",
     }, {
          "country": "Bahamas",
     }, {
          "country": "Bahrain",
     }, {
          "country": "Bangladesh",
     }, {
          "country": "Barbados",
     }, {
          "country": "Belarus",
     }, {
          "country": "Belgium",
     }, {
          "country": "Belize",
     }, {
          "country": "Benin",
     }, {
          "country": "Bhutan",
     }, {
          "country": "Bolivia",
     }, {
          "country": "Bosnia",
     }, {
          "country": "Botswana",
     }, {
          "country": "Brazil",
     }, {
          "country": "Brunei",
     }, {
          "country": "Bulgaria",
     }, {
          "country": "Burkina Faso",
     }, {
          "country": "Burundi",
     }, {
          "country": "Cabo Verde",
     }, {
          "country": "Cambodia",
     }, {
          "country": "Cameroon",
     }, {
          "country": "Canada",
     }, {
          "country": "Central African Republic",
     }, {
          "country": "Chad",
     }, {
          "country": "Chile",
     }, {
          "country": "China",
     }, {
          "country": "Colombia",
     }, {
          "country": "Comoros",
     }, {
          "country": "Congo",
     }, {
          "country": "DRC",
     }, {
          "country": "Costa Rica",
     }, {
          "country": "Côte d'Ivoire",
     }, {
          "country": "Croatia",
     }, {
          "country": "Cuba",
     }, {
          "country": "Cyprus",
     }, {
          "country": "Czechia",
     }, {
          "country": "Denmark",
     }, {
          "country": "Diamond Princess",
     }, {
          "country": "Djibouti",
     }, {
          "country": "Dominica",
     }, {
          "country": "Dominican Republic",
     }, {
          "country": "Ecuador",
     }, {
          "country": "Egypt",
     }, {
          "country": "El Salvador",
     }, {
          "country": "Equatorial Guinea",
     }, {
          "country": "Eritrea",
     }, {
          "country": "Estonia",
     }, {
          "country": "Swaziland",
     }, {
          "country": "Ethiopia",
     }, {
          "country": "Fiji",
     }, {
          "country": "Finland",
     }, {
          "country": "France",
     }, {
          "country": "Gabon",
     }, {
          "country": "Gambia",
     }, {
          "country": "Georgia",
     }, {
          "country": "Germany",
     }, {
          "country": "Ghana",
     }, {
          "country": "Greece",
     }, {
          "country": "Grenada",
     }, {
          "country": "Guatemala",
     }, {
          "country": "Guinea",
     }, {
          "country": "Guinea-Bissau",
     }, {
          "country": "Guyana",
     }, {
          "country": "Haiti",
     }, {
          "country": "Honduras",
     }, {
          "country": "Hungary",
     }, {
          "country": "Iceland",
     }, {
          "country": "India",
     }, {
          "country": "Indonesia",
     }, {
          "country": "Iran",
     }, {
          "country": "Iraq",
     }, {
          "country": "Ireland",
     }, {
          "country": "Israel",
     }, {
          "country": "Italy",
     }, {
          "country": "Jamaica",
     }, {
          "country": "Japan",
     }, {
          "country": "Jordan",
     }, {
          "country": "Kazakhstan",
     }, {
          "country": "Kenya",
     }, {
          "country": "S. Korea",
     }, {
          "country": "Kuwait",
     }, {
          "country": "Kyrgyzstan",
     }, {
          "country": "Lao People's Democratic Republic",
     }, {
          "country": "Latvia",
     }, {
          "country": "Lebanon",
     }, {
          "country": "Lesotho",
     }, {
          "country": "Liberia",
     }, {
          "country": "Libyan Arab Jamahiriya",
     }, {
          "country": "Liechtenstein",
     }, {
          "country": "Lithuania",
     }, {
          "country": "Luxembourg",
     }, {
          "country": "MS Zaandam",
     }, {
          "country": "Madagascar",
     }, {
          "country": "Malawi",
     }, {
          "country": "Malaysia",
     }, {
          "country": "Maldives",
     }, {
          "country": "Mali",
     }, {
          "country": "Malta",
     }, {
          "country": "Marshall Islands",
     }, {
          "country": "Mauritania",
     }, {
          "country": "Mauritius",
     }, {
          "country": "Mexico",
     }, {
          "country": "Moldova",
     }, {
          "country": "Monaco",
     }, {
          "country": "Mongolia",
     }, {
          "country": "Montenegro",
     }, {
          "country": "Morocco",
     }, {
          "country": "Mozambique",
     }, {
          "country": "Namibia",
     }, {
          "country": "Nepal",
     }, {
          "country": "Netherlands",
     }, {
          "country": "New Zealand",
     }, {
          "country": "Nicaragua",
     }, {
          "country": "Niger",
     }, {
          "country": "Nigeria",
     }, {
          "country": "Macedonia",
     }, {
          "country": "Norway",
     }, {
          "country": "Oman",
     }, {
          "country": "Pakistan",
     }, {
          "country": "Panama",
     }, {
          "country": "Papua New Guinea",
     }, {
          "country": "Paraguay",
     }, {
          "country": "Peru",
     }, {
          "country": "Philippines",
     }, {
          "country": "Poland",
     }, {
          "country": "Portugal",
     }, {
          "country": "Qatar",
     }, {
          "country": "Romania",
     }, {
          "country": "Russia",
     }, {
          "country": "Rwanda",
     }, {
          "country": "Saint Kitts and Nevis",
     }, {
          "country": "Saint Lucia",
     }, {
          "country": "Saint Vincent and the Grenadines",
     }, {
          "country": "Samoa",
     }, {
          "country": "San Marino",
     }, {
          "country": "Sao Tome and Principe",
     }, {
          "country": "Saudi Arabia",
     }, {
          "country": "Senegal",
     }, {
          "country": "Serbia",
     }, {
          "country": "Seychelles",
     }, {
          "country": "Sierra Leone",
     }, {
          "country": "Singapore",
     }, {
          "country": "Slovakia",
     }, {
          "country": "Slovenia",
     }, {
          "country": "Solomon Islands",
     }, {
          "country": "Somalia",
     }, {
          "country": "South Africa",
     }, {
          "country": "South Sudan",
     }, {
          "country": "Spain",
     }, {
          "country": "Sri Lanka",
     }, {
          "country": "Sudan",
     }, {
          "country": "Suriname",
     }, {
          "country": "Sweden",
     }, {
          "country": "Switzerland",
     }, {
          "country": "Syrian Arab Republic",
     }, {
          "country": "Taiwan",
     }, {
          "country": "Tajikistan",
     }, {
          "country": "Tanzania",
     }, {
          "country": "Thailand",
     }, {
          "country": "Timor-Leste",
     }, {
          "country": "Togo",
     }, {
          "country": "Trinidad and Tobago",
     }, {
          "country": "Tunisia",
     }, {
          "country": "Turkey",
     }, {
          "country": "USA",
     }, {
          "country": "Uganda",
     }, {
          "country": "Ukraine",
     }, {
          "country": "UAE",
     }, {
          "country": "UK",
     }, {
          "country": "Uruguay",
     }, {
          "country": "Uzbekistan",
     }, {
          "country": "Vanuatu",
     }, {
          "country": "Venezuela",
     }, {
          "country": "Vietnam",
     }, {
          "country": "Yemen",
     }, {
          "country": "Zambia",
     }, {
          "country": "Zimbabwe",
     }
]
